import * as THREE from 'three';
import { renderToCube } from '../gfx/cubeBake.js';
import { BAKE_VERT, BAKE_FRAG } from './planetBakeShader.js';
import {
  SURFACE_VERT, SURFACE_FRAG, PLAIN_VERT,
  CLOUD_VERT, CLOUD_FRAG,
  ATMO_VERT, ATMO_FRAG,
  GAS_FRAG, RING_VERT, RING_FRAG,
} from './planetShaders.js';

/* ============================================================================
   A world.

   Hierarchy (everything below `group` lives in unit-radius object space):

     group  position = world position, quaternion = axial tilt, scale = radius
       ├── surface   unit sphere, displaced from the baked height channel
       ├── clouds    unit sphere @ 1.012
       ├── atmo      unit sphere @ 1 + atmosphere height
       └── rings     annulus in the equatorial plane

   The planet's *rotation* is a shader uniform rather than a transform, so the
   ring-shadow and cloud-shadow maths all share one consistent frame.
   ========================================================================== */

/* three's `detail` is *not* a subdivision count. PolyhedronGeometry cuts each
   of the 20 base faces into (detail+1)^2 sub-triangles, so detail 5 — which
   reads like a lot — is 720 triangles and a silhouette of about two dozen
   straight edges. On a world that fills the frame that polygon is plainly
   visible, and anything raised to a high power against the limb (the
   atmosphere's halo, the gas giant's haze rim) traces it in bright pixels:
   that is the "hard bright halo with visible stepping" round every giant.

   Triangles are the one thing this renderer has in surplus — the frame already
   draws half a million of them and these shaders are fill-bound, not
   vertex-bound — so the ladder below is roughly an order of magnitude more
   generous and costs nothing measurable. */
const _geoCache = new Map();
function icoGeo(level) {
  if (!_geoCache.has(level)) _geoCache.set(level, new THREE.IcosahedronGeometry(1, level));
  return _geoCache.get(level);
}
const LOD_NEAR = 16;   // 5 780 tris — a world filling the frame, limb smooth
   // to a third of a pixel
const LOD_MID = 9;     // 2 000 tris
const LOD_FAR = 5;     //   720 tris — what every mesh here used to be

/* The ring shader reads the fragment's radius straight out of object space, so
   the annulus has to actually span inner..outer in planet radii — a unit ring
   scaled up would put every fragment at exactly one radius. */
function ringGeo(inner, outer) {
  const g = new THREE.RingGeometry(inner, outer, 384, 6);
  g.rotateX(-Math.PI / 2);
  return g;
}

const _m3 = new THREE.Matrix3();
const _m4 = new THREE.Matrix4();
const _v3 = new THREE.Vector3();
const _v3b = new THREE.Vector3();
const _q = new THREE.Quaternion();

export class Planet {
  /**
   * @param {object} spec  generated by SystemGen
   * @param {object} ctx   { envMap, quality }
   */
  constructor(spec, ctx) {
    this.spec = spec;
    this.name = spec.name;
    this.type = spec.type;
    this.radius = spec.radius;
    this.isGas = spec.type === 'gas';
    this.absPos = new THREE.Vector3();
    this.spin = Math.random() * Math.PI * 2;
    this.spinRate = spec.spinRate;
    this.cloudSpin = 0;
    this.scanned = false;
    this.bakeRes = 0;
    this.surfCube = null;
    this._detail = 0;

    this.group = new THREE.Group();
    this.group.scale.setScalar(this.radius);
    this.group.quaternion.setFromAxisAngle(
      new THREE.Vector3(Math.cos(spec.tiltDir), 0, Math.sin(spec.tiltDir)).normalize(),
      spec.tilt
    );
    this.group.matrixAutoUpdate = true;

    const env = ctx.envMap;
    const q = ctx.quality;
    this.quality = q;

    /* The colour of this world's own sky, which is what its oceans reflect and
       what its haze is made of. Rayleigh scattering is stronger the shorter the
       wavelength, so the normalised extinction coefficients *are* the sky. */
    const sky = new THREE.Color(0.20, 0.44, 1.0);
    if (spec.atmo) {
      const b = spec.atmo.betaR;
      const m = Math.max(b.x, b.y, b.z, 1e-4);
      sky.setRGB(b.x / m, b.y / m, b.z / m);
    }
    this.skyCol = sky;
    // Limb darkening exponent. A hazy world rolls off hard toward the limb; an
    // airless one barely does at all — the Moon at full really is a flat disc —
    // but it still needs enough to separate the silhouette from the void.
    this._limb = spec.atmo ? 0.95 : 0.48;

    // ---------------------------------------------------------- surface
    if (this.isGas) {
      this.surfMat = new THREE.ShaderMaterial({
        vertexShader: PLAIN_VERT,
        fragmentShader: GAS_FRAG,
        uniforms: {
          uSunDir: { value: new THREE.Vector3(1, 0, 0) },
          uSunColor: { value: new THREE.Color(1, 1, 1) },
          uCamPos: { value: new THREE.Vector3() },
          uTime: { value: 0 },
          uSeed: { value: spec.seed },
          uC0: { value: spec.colors.c0 }, uC1: { value: spec.colors.c1 },
          uC2: { value: spec.colors.c2 }, uC3: { value: spec.colors.c3 },
          uAmbient: { value: new THREE.Color(0.02, 0.025, 0.04) },
          uStorm: { value: spec.storm },
          uBands: { value: spec.bands },
          uDetail: { value: 0 },
          uObjFromWorld: { value: new THREE.Matrix3() },
          uRingInner: { value: 0 }, uRingOuter: { value: 0 }, uRingOpacity: { value: 0 },
          uEnv: { value: env },
        },
      });
    } else {
      this.surfMat = new THREE.ShaderMaterial({
        vertexShader: SURFACE_VERT,
        fragmentShader: SURFACE_FRAG,
        uniforms: {
          uSurf: { value: null },
          uEnv: { value: env },
          uSunDir: { value: new THREE.Vector3(1, 0, 0) },
          uSunColor: { value: new THREE.Color(1, 1, 1) },
          uCamPos: { value: new THREE.Vector3() },
          uCamObj: { value: new THREE.Vector3() },
          uTexel: { value: 1 / 256 },
          uBump: { value: spec.bump },
          /* Silhouette displacement, in planet radii. Airless rock gets all of
             it — a small moon really is a percent out of round and its limb is
             notched by crater rims, and that irregular edge is most of what
             says "solid body" rather than "sphere with a texture on it". A
             world with air gets a quarter: those are large and smooth, and the
             cloud deck sits only 2.4 percent up, so a peak that big would push
             through its own weather. */
          uDisp: { value: spec.disp * (spec.atmo ? 0.25 : 1.0) },
          uSea: { value: spec.sea },
          uType: { value: spec.typeId },
          uTime: { value: 0 },
          uDetail: { value: 0 },
          uSharp: { value: 0 },
          uLimb: { value: this._limb },
          uSeed: { value: spec.seed },
          uWaterCol: { value: spec.colors.water },
          uSkyCol: { value: sky },
          uHasAtmo: { value: spec.atmo ? 1 : 0 },
          uAmbient: { value: new THREE.Color(0.018, 0.022, 0.035) },
          uNight: { value: spec.night },
          uLavaGlow: { value: spec.lavaGlow },
          uCloudShadow: { value: spec.clouds ? 0.88 : 0 },
          uCloudAlt: { value: spec.clouds ? spec.clouds.alt : 0.012 },
          uCloudRot: { value: 0 },
          uCloudScale: { value: spec.clouds ? spec.clouds.scale : 1 },
          uCloudCover: { value: spec.clouds ? spec.clouds.cover : 0.5 },
          uRingInner: { value: 0 }, uRingOuter: { value: 0 }, uRingOpacity: { value: 0 },
          uObjFromWorld: { value: new THREE.Matrix3() },
          uSpin: { value: 0 },
        },
      });
    }
    this.surface = new THREE.Mesh(icoGeo(LOD_FAR), this.surfMat);
    this.surface.renderOrder = 0;
    this.surface.frustumCulled = false;
    this.group.add(this.surface);

    // ---------------------------------------------------------- clouds
    if (spec.clouds) {
      this.cloudMat = new THREE.ShaderMaterial({
        vertexShader: CLOUD_VERT,
        fragmentShader: CLOUD_FRAG,
        transparent: true,
        depthWrite: false,
        blending: THREE.CustomBlending,
        blendSrc: THREE.OneFactor,
        blendDst: THREE.OneMinusSrcAlphaFactor,
        uniforms: {
          uSunDir: { value: new THREE.Vector3(1, 0, 0) },
          uSunColor: { value: new THREE.Color(1, 1, 1) },
          uCamPos: { value: new THREE.Vector3() },
          uCamObj: { value: new THREE.Vector3() },
          uTime: { value: 0 },
          uSeed: { value: spec.seed },
          uRot: { value: 0 },
          uScale: { value: spec.clouds.scale },
          uCover: { value: spec.clouds.cover },
          uShellR: { value: 1 + spec.clouds.alt },
          uThick: { value: spec.clouds.thick },
          uTint: { value: spec.clouds.tint },
          uAmbient: { value: new THREE.Color(0.03, 0.035, 0.055) },
          uObjFromWorld: { value: new THREE.Matrix3() },
          uRingInner: { value: 0 }, uRingOuter: { value: 0 }, uRingOpacity: { value: 0 },
        },
      });
      this.clouds = new THREE.Mesh(icoGeo(LOD_FAR), this.cloudMat);
      this.clouds.scale.setScalar(1.0 + spec.clouds.alt);
      this.clouds.renderOrder = 4;
      this.clouds.frustumCulled = false;
      this.group.add(this.clouds);
    }

    // ------------------------------------------------------ atmosphere
    if (spec.atmo) {
      const a = spec.atmo;
      /* The generated shells are deliberately ~1.7x taller than the real ratio
         so the halo is visible at all — but the *scale height* was scaled up
         with them, which left every world wrapped in a fog ball about twelve
         times deeper than Earth's air. That is what made the atmosphere read as
         a symmetric decal ring: with the scattering spread evenly through the
         whole shell, the limb starts brightening from halfway across the disc
         and by the edge it is twice the disc centre, which drowns every bit of
         shading underneath it and leaves a uniformly lit blue circle.

         Compressing the profile back toward the ground and paying for the lost
         optical depth with the coefficients keeps the zenith colour exactly
         where it was, but turns the broad glow into a thin bright arc and lets
         the surface's own terminator through. */
      const HR = 0.56, HM = 0.62;
      this.atmoMat = new THREE.ShaderMaterial({
        vertexShader: ATMO_VERT,
        fragmentShader: ATMO_FRAG,
        transparent: true,
        depthWrite: false,
        side: THREE.FrontSide,
        blending: THREE.CustomBlending,
        blendSrc: THREE.OneFactor,
        blendDst: THREE.OneMinusSrcAlphaFactor,
        blendSrcAlpha: THREE.OneFactor,
        blendDstAlpha: THREE.OneMinusSrcAlphaFactor,
        uniforms: {
          uCamObj: { value: new THREE.Vector3() },
          uSunObj: { value: new THREE.Vector3(1, 0, 0) },
          uSunColor: { value: new THREE.Color(1, 1, 1) },
          uAtmoR: { value: 1 + a.height },
          uBetaR: { value: a.betaR.clone().divideScalar(HR) },
          uBetaM: { value: a.betaM / HM },
          // Ozone: absorbs without scattering, and does it in the green and
          // orange rather than the blue, which is why a real twilight band is
          // violet instead of grey and why a long limb path loses its warmth
          // before it loses its blue. The spectral shape is fixed; only the
          // amount scales with how much air this world has.
          uBetaO: {
            value: new THREE.Vector3(0.36, 0.86, 0.035)
              .multiplyScalar(a.betaR.length() * 0.075 / HR),
          },
          uHr: { value: a.hr * HR },
          uHm: { value: a.hm * HM },
          uG: { value: a.g },
          // The shell used to be bright enough that every part of it sat on the
          // flat top of the tone curve: a full-phase world came out as one even
          // blue disc with a ring of the same blue around it, and no amount of
          // shading underneath could show through. Pulling the level down puts
          // the gradient back on the steep part of the curve, where the
          // difference between a sunward limb and a night limb is visible.
          uIntensity: { value: a.intensity * 0.40 },
        },
        defines: {
          ATMO_STEPS: q === 'low' ? 8 : q === 'medium' ? 12 : 16,
          ATMO_LSTEPS: q === 'low' ? 2 : q === 'medium' ? 3 : 4,
        },
      });
      this.atmo = new THREE.Mesh(icoGeo(LOD_FAR), this.atmoMat);
      this.atmo.scale.setScalar(1 + a.height);
      this.atmo.renderOrder = 5;
      this.atmo.frustumCulled = false;
      this.group.add(this.atmo);
    }

    // ----------------------------------------------------------- rings
    if (spec.rings) {
      const r = spec.rings;
      this.ringMat = new THREE.ShaderMaterial({
        vertexShader: RING_VERT,
        fragmentShader: RING_FRAG,
        transparent: true,
        depthWrite: false,
        side: THREE.DoubleSide,
        blending: THREE.CustomBlending,
        blendSrc: THREE.OneFactor,
        blendDst: THREE.OneMinusSrcAlphaFactor,
        uniforms: {
          uSunObj: { value: new THREE.Vector3(1, 0, 0) },
          uSunColor: { value: new THREE.Color(1, 1, 1) },
          uCamObj: { value: new THREE.Vector3() },
          uInner: { value: r.inner },
          uOuter: { value: r.outer },
          uSeed: { value: spec.seed * 1.7 },
          uColA: { value: r.colA },
          uColB: { value: r.colB },
          uOpacity: { value: r.opacity },
          uAmbient: { value: new THREE.Color(0.02, 0.024, 0.04) },
          uAtmoR: { value: spec.atmo ? 1 + spec.atmo.height : 1.0 },
        },
      });
      this.rings = new THREE.Mesh(ringGeo(r.inner, r.outer), this.ringMat);
      this.rings.renderOrder = 6;
      this.rings.frustumCulled = false;
      this.group.add(this.rings);

      // feed the ring geometry back into the surface *and cloud* shaders for
      // shadowing — the deck is as much a surface the ring falls on as the
      // ground is, and it is the one you actually see on a world with weather.
      for (const m of [this.surfMat, this.cloudMat]) {
        if (!m) continue;
        m.uniforms.uRingInner.value = r.inner;
        m.uniforms.uRingOuter.value = r.outer;
        m.uniforms.uRingOpacity.value = r.opacity;
      }
    }
  }

  /** Bake (or re-bake at a new resolution) the surface cubemap. */
  bake(renderer, res) {
    if (this.isGas || this.bakeRes === res) return;
    const s = this.spec;
    const mat = new THREE.ShaderMaterial({
      vertexShader: BAKE_VERT,
      fragmentShader: BAKE_FRAG,
      uniforms: {
        uSeed: { value: s.seed },
        uType: { value: s.typeId },
        uVariant: { value: s.variant | 0 },
        uSea: { value: s.sea },
        uIce: { value: s.ice },
        uRelief: { value: s.relief },
        uCraters: { value: s.craters },
        uVeg: { value: s.veg },
        uC0: { value: s.colors.c0 }, uC1: { value: s.colors.c1 },
        uC2: { value: s.colors.c2 }, uC3: { value: s.colors.c3 },
        uC4: { value: s.colors.c4 },
        uCPolar: { value: s.colors.polar },
        uCWater: { value: s.colors.water },
        uDetailFreq: { value: s.detailFreq },
      },
    });
    const rt = renderToCube(renderer, mat, res);
    mat.dispose();
    if (this.surfCube) this.surfCube.dispose();
    this.surfCube = rt;
    this.bakeRes = res;
    this.surfMat.uniforms.uSurf.value = rt.texture;
    this.surfMat.uniforms.uTexel.value = 1 / res;
  }

  /**
   * @param {number} dt
   * @param {object} ctx  { origin, camPos, sunPos, sunColor, time, ambient }
   */
  update(dt, ctx) {
    this.spin = (this.spin + this.spinRate * dt) % (Math.PI * 2);
    this.cloudSpin = (this.cloudSpin + this.spinRate * 1.28 * dt) % (Math.PI * 2);

    this.group.position.copy(this.absPos).sub(ctx.origin);
    this.group.updateMatrixWorld(true);

    // world -> object rotation
    _m4.copy(this.group.matrixWorld);
    const inv = _m4.invert();
    _m3.setFromMatrix4(inv);
    // strip the 1/radius scale so the matrix is a pure rotation
    _m3.multiplyScalar(this.radius);

    const camLocal = _v3.copy(ctx.camPos).sub(this.group.position);
    const dist = camLocal.length();
    this.distance = dist;
    this.altitude = dist - this.radius;
    this.angularSize = 2 * Math.atan(this.radius / Math.max(dist, this.radius * 1.0001));

    // camera in object space, radius units
    const camObj = _v3b.copy(camLocal).applyMatrix3(_m3).divideScalar(this.radius);

    // sun direction (world), pointing from planet toward the star
    const sunDirW = new THREE.Vector3().copy(ctx.sunPos).sub(this.absPos).normalize();
    const sunObj = sunDirW.clone().applyMatrix3(_m3);

    const u = this.surfMat.uniforms;
    u.uSunDir.value.copy(sunDirW);
    u.uSunColor.value.copy(ctx.sunColor);
    u.uCamPos.value.copy(ctx.camPos);
    u.uTime.value = ctx.time;
    u.uObjFromWorld.value.copy(_m3);
    u.uAmbient.value.copy(ctx.ambient);
    /* Sub-texel relief blends in over the approach. Driven by angular size so
       it tracks how big a bake texel is *on screen* — the old altitude ramp
       only reached a tenth of a radius up, which is below where anyone
       actually flies, so the extra relief was never once seen.

       The onset is late on purpose. This block is three noise taps over every
       pixel of the planet, and at three radii out the 1024-per-face bake is
       still finer than a pixel, so all it buys there is a third of the frame.
       A gas giant has no bake at all but the same problem — its band texture
       bottoms out well above the pixel — so it rides the same ramp. */
    /* A giant needs it earlier than a baked world does. Its band texture
       bottoms out around a thirtieth of a radius against a 1024-per-face
       bake's texel, so at 1.7 radii — where a close pass actually happens —
       the shared ramp was only a third on and the belt interiors stayed
       laminar exactly where the disc fills the frame. It still switches off
       well before three radii, which is where the far banding already reads. */
    const a0 = this.isGas ? 0.62 : 0.80, a1 = this.isGas ? 1.22 : 1.45;
    const want = THREE.MathUtils.smoothstep(this.angularSize, a0, a1);
    this._detail = THREE.MathUtils.lerp(this._detail, want, 0.12);
    u.uDetail.value = this._detail;

    if (!this.isGas) {
      u.uCamObj.value.copy(camObj);
      u.uSpin.value = this.spin;
      u.uCloudRot.value = this.cloudSpin;

      // Coastline re-synthesis rides on *angular size*, not altitude: it exists
      // to hide the bake's texel grid, which only becomes visible once the
      // planet is large in frame. Ramping it in from a distance would just add
      // high-frequency noise to a disc a hundred pixels wide, and that crawls.
      u.uSharp.value = THREE.MathUtils.smoothstep(this.angularSize, 0.10, 0.50);

    }

    /* One LOD decision for all three shells, and it has to reach the clouds and
       the atmosphere too: they were built at a fixed level, so a system with
       sixteen bodies in it paid the close-up triangle count on every distant
       speck three times over. Nothing is frustum-culled here either, so that
       cost is unconditional. */
    {
      const want = this.angularSize > 0.22 ? (this.quality === 'low' ? LOD_MID : LOD_NEAR)
        : this.angularSize > 0.035 ? (this.quality === 'low' ? LOD_FAR : LOD_MID)
          : LOD_FAR;
      const g = icoGeo(want);
      if (this.surface.geometry !== g) this.surface.geometry = g;
      if (this.clouds && this.clouds.geometry !== g) this.clouds.geometry = g;
      if (this.atmo && this.atmo.geometry !== g) this.atmo.geometry = g;
    }

    if (this.clouds) {
      const cu = this.cloudMat.uniforms;
      cu.uSunDir.value.copy(sunDirW);
      cu.uSunColor.value.copy(ctx.sunColor);
      cu.uCamPos.value.copy(ctx.camPos);
      cu.uTime.value = ctx.time;
      cu.uRot.value = this.cloudSpin;
      cu.uCamObj.value.copy(camObj);
      cu.uAmbient.value.copy(ctx.ambient).multiplyScalar(1.6);
      cu.uObjFromWorld.value.copy(_m3);
      this.clouds.visible = this.angularSize > 0.012 && !this._noClouds;
    }

    if (this.atmo) {
      const au = this.atmoMat.uniforms;
      au.uCamObj.value.copy(camObj);
      au.uSunObj.value.copy(sunObj);
      au.uSunColor.value.copy(ctx.sunColor);
      const inside = camObj.length() < this.atmoMat.uniforms.uAtmoR.value * 1.001;
      const wantSide = inside ? THREE.BackSide : THREE.FrontSide;
      if (this.atmoMat.side !== wantSide) {
        this.atmoMat.side = wantSide;
        this.atmoMat.depthTest = !inside;
        this.atmoMat.needsUpdate = true;
      }
    }

    if (this.rings) {
      const ru = this.ringMat.uniforms;
      ru.uSunObj.value.copy(sunObj);
      ru.uSunColor.value.copy(ctx.sunColor);
      ru.uCamObj.value.copy(camObj);
      ru.uAmbient.value.copy(ctx.ambient);
    }
  }

  dispose() {
    this.rings?.geometry.dispose();
    this.surfCube?.dispose();
    this.surfMat?.dispose();
    this.cloudMat?.dispose();
    this.atmoMat?.dispose();
    this.ringMat?.dispose();
  }
}
